config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, numericality: { greater_than: 0 }
  validates :number_of_guests, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>All our Flats ( <%= @flats.count %> )</h1>
<br>

<%= link_to "add a flat", new_flat_path  %>

<% @flats.each do |flat| %>

<div class="card-trip">
  <div class="card-trip-infos">
    <div>
      <h2> <%= flat.name %> </h2>
      <p><%= flat.address %></p>
    </div>
    <h2 class="card-trip-pricing">€ <%= flat.price_per_night %></h2>
    <h2 class="card-trip-pricing">🦸 <%= flat.number_of_guests %></h2>
  </div>
  <%= link_to "more info", flat_path(flat)  %>
</div>
<br>

<% end %>

app/views/flats/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= simple_form_for @flat do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.submit "create", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<h1>detailed infos</h1>

<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="card p-2">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="card p-2">
        <h1>A bit more about this flat...</h1>
        <p><%= @flat.description %></p>
      </div>
      <div class="card p-2">
        <h1>Details</h1>
        <div class="d-flex">
          <p class="d-inline"><%= @flat.number_of_guests %></p>
          <p class="d-inline">€ <%= @flat.price_per_night %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>